name: mac.yml
on: push

jobs:
  build:
    name: Build on Mac OS
    runs-on: macos-15
    steps:
      - name: Check path
        run: bash -c 'ls -la /usr/bin/llvm-gcc; llvm-gcc --version; find ${PATH//:/\/ } -name llvm-*; ls $(brew --prefix llvm@18)/bin/; ls $(brew --prefix llvm)/bin/ true'
