name: mac.yml
on: push

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Check path
        run: |
          ls
          . "./a.ps1"
